llm:
  provider: "deepseek"
  name: "deepseek-chat"
  temperature: 0.0
  top_p: 1.0
browser:
  name: "chrome"
  wait_for_timeout: 1000
fields:
  article_body:
    strategy: "xpath_extractor"
  title:
    strategy: "lm_capabilities"
  author:
    strategy: "lm_capabilities"
  datetime:
    strategy: "lm_capabilities"